export const DOMAIN_EVENT_NAMES = [
  "task.created", "task.updated", "task.completed", "task.reopened", "task.deleted", "task.assigned", "task.unassigned", "task.due_date_changed",
  "project.created", "project.updated", "project.archived", "project.completed", "project.progress_updated", "task.assigned_to_project", "task.removed_from_project", "task.created_from_subscription",
  "client.created", "client.updated", "client.deleted", "deal.created", "deal.updated", "deal.stage_changed", "deal.won", "deal.lost", "deal.deleted",
  "payment.received", "payment.sent", "money.transaction.created", "money.transaction.updated", "transaction.deleted", "account.created", "account.updated", "account.deactivated", "category.created",
  "subscription.created", "subscription.updated", "subscription.deleted", "subscription.renewed", "subscription.expired", "subscription.plan_changed", "subscription.canceled", "subscription.cancelled",
  "subscription.payment_cycle.created", "subscription.payment_cycle.paid", "subscription.payment_cycle.skipped", "subscription.payment_due_date.changed", "subscription.payment_task.created",
  "subscription_task_suggestion.created", "subscription_task_suggestion.confirmed",
  "billing.subscription.created", "billing.subscription.updated", "billing.subscription.canceled", "billing.plan.changed", "billing.payment.succeeded", "billing.payment.failed", "billing.limit.exceeded", "billing.trial.expired",
  "billing.trial.claimed", "billing.trial.denied", "billing.trial.consumed", "billing.plan.required",
  "pricing_viewed", "checkout_started", "checkout_completed", "checkout_failed", "customer_portal_opened", "upgrade_prompt_viewed", "upgrade_prompt_clicked", "limit_reached", "trial_started", "trial_expired", "trial_reuse_blocked", "subscription_cancelled", "subscription_updated",
  "report.created", "snapshot.created", "insights.generated", "recommendations.generated", "summary.generated", "recommendation.dismissed",
  "document.created", "document.updated", "document.deleted", "document.attachment_uploaded", "document.linked",
  "document.extraction.started", "document.extraction.completed", "document.extraction.failed",
  "document.financial_data_extracted", "document.detected_financial_data",
  "financial_obligation.detected", "financial_obligation.confirmed", "financial_obligation.dismissed", "financial_obligation.task_created", "financial_obligation.paid", "financial_obligation.skipped",
  "financial_task.created", "financial_task.completed", "financial_task.skipped", "financial_task.dismissed", "financial_task.due_date_changed", "financial_task.amount_set",
  "money.transaction.draft_created", "money.transaction.confirmed", "money.transaction.rejected", "transaction.created_from_suggestion",
  "money.transfer.created",
  "money.transaction.categorization_requested", "money.transaction.categorized", "money.transaction.category_changed",
  "money.ai_suggestion.created", "money.ai_suggestion.accepted", "money.ai_suggestion.rejected", "money.ai_suggestion.expired",
  "money.category_rule.created", "money.category_rule.updated", "money.category_rule.disabled", "money.category_rule.enabled", "money.category_rule.deleted",
  "money.transaction.auto_categorization_requested",
  "financial_suggestion.created", "financial_suggestion.edited", "financial_suggestion.confirmed", "financial_suggestion.rejected",
  "action_center.item_created",
  "planner_entry.created", "planner_entry.processing_started", "planner_entry.processed", "planner_entry.failed",
  "planner_suggestion.created", "planner_suggestion.accepted", "planner_suggestion.edited", "planner_suggestion.rejected", "planner_suggestion.failed", "planner_suggestion.expired",
  "onboarding.first_action_selected", "onboarding.first_action_completed", "onboarding.first_workflow_completed", "onboarding.dismissed",
  "org.created", "org.updated", "member.invited", "member.joined", "member.removed", "member.role_changed", "workspace.created",
  "user.deletion_requested", "user.deletion_cancelled", "user.deletion_purged",
  "booking.requested", "booking.request.accepted", "booking.request.rejected", "booking.request.canceled", "booking.host_profile.created", "booking.host_profile.updated", "booking.service.created", "booking.availability.updated", "crm.lead.created_from_booking", "booking.request.linked_to_crm_lead",
  "relation.created", "relation.deleted", "relation.updated", "relation.auto_created", "relation.suggested", "relation.confirmed", "relation.rejected", "relation.unlinked",
  "action_item.created", "action_item.assigned", "action_item.snoozed", "action_item.resolved", "action_item.dismissed", "action_item.executed", "action_item.failed", "action_item.restored",
] as const;

export type DomainEventName = (typeof DOMAIN_EVENT_NAMES)[number];
