/** Compatibility facade; canonical MoneyFlow constants live in the workspace package. */
export {
  ACCOUNT_TYPES,
  TRANSACTION_TYPES,
  TRANSFER_TYPE,
  ALL_TRANSACTION_TYPES,
  TRANSACTION_STATUSES,
  CATEGORY_TYPES,
  CATEGORIZATION_STATUSES,
  CATEGORY_SOURCES,
  SUGGESTION_STATUSES,
  CONFIDENCE_HIGH,
  CONFIDENCE_MIN_SUGGESTION,
  DEFAULT_CURRENCY,
  MONEY_ACCOUNT_CURRENCIES,
  ACCOUNT_NAME_MAX,
  CATEGORY_NAME_MAX,
  TRANSACTION_TITLE_MAX,
  TRANSACTION_NOTE_MAX,
} from "@nevora/finance-contracts";
export type {
  AccountType,
  TransactionType,
  AnyTransactionType,
  TransactionStatus,
  CategoryType,
  CategorizationStatus,
  CategorySource,
  SuggestionStatus,
  MoneyAccountCurrency,
} from "@nevora/finance-contracts";
