-- ============================================================
-- Migration 079: Financial Context Tasks
-- ============================================================
-- Turns generic todos into an operational layer for Business OS: a task can now
-- carry FINANCIAL CONTEXT (a real payment/deadline it stands in for) in addition
-- to its own action deadline.
--
--   document upload -> AI/OCR detects a financial obligation
--   -> (user confirms)  -> financial task (due 3 days before the payment date)
--   -> "Mark as paid"   -> ONE posted expense transaction -> task done
--
-- Design decision (see audit): we do NOT introduce a parallel `financial_obligations`
-- table. Recurring obligations already live in `subscription_payment_cycles`
-- (migration 078); one-off obligations (tax notice, domain renewal, client-invoice
-- follow-up) are represented directly as a financial task + entity_links to their
-- source document. The task row itself is the single source of truth for
-- "is this obligation paid".
--
-- Core rule (unchanged): AI/document detection NEVER posts a money transaction.
-- A posted expense is created ONLY by an explicit Mark-as-paid, and that creation
-- is idempotent (guarded by todos.financial_transaction_id + a row lock in the RPC).
--
-- This migration:
--   A. Extends public.todos with financial-context columns (+ CHECK dictionaries).
--   B. Indexes the "financial tasks" access path.
--   C. Recreates the task_smart_list view so t.* re-expands to the new columns.
--   D. mark_financial_task_paid() — atomic, idempotent one-off Mark-as-paid RPC.
--
-- Subscription payment tasks keep using mark_subscription_payment_paid (078);
-- this RPC is only for one-off financial tasks that have no payment cycle.

BEGIN;

-- ============================================================
-- A. Financial-context columns on todos
-- ============================================================
-- Query-critical fields (context type, financial due date, amount, currency,
-- status) live as real columns — they drive the "Financial Tasks" filter,
-- dashboards and the Mark-as-paid RPC and must not be buried in jsonb.
ALTER TABLE public.todos
  -- What kind of obligation this task represents. 'standard' = an ordinary task
  -- (the default, so existing rows are untouched and behave exactly as before).
  ADD COLUMN IF NOT EXISTS task_context_type TEXT NOT NULL DEFAULT 'standard'
    CHECK (task_context_type IN (
      'standard',
      'subscription_payment',
      'invoice_payment',
      'tax_payment',
      'domain_renewal',
      'hosting_payment',
      'client_invoice_followup',
      'expense_review',
      'document_review'
    )),
  -- The real payment/deadline date the obligation must be settled by. due_date
  -- (the task's own deadline) is derived as financial_due_date - reminder_offset_days.
  ADD COLUMN IF NOT EXISTS financial_due_date DATE,
  ADD COLUMN IF NOT EXISTS reminder_offset_days INTEGER NOT NULL DEFAULT 3
    CHECK (reminder_offset_days BETWEEN 0 AND 365),
  ADD COLUMN IF NOT EXISTS amount NUMERIC(14, 2)
    CHECK (amount IS NULL OR amount >= 0),
  ADD COLUMN IF NOT EXISTS currency TEXT,
  ADD COLUMN IF NOT EXISTS provider_name TEXT,
  -- Where the obligation came from. 'document' = detected from an uploaded doc,
  -- 'subscription_payment_cycle' = generated by the subscription workflow,
  -- 'manual' = created by hand in the financial-task UI.
  ADD COLUMN IF NOT EXISTS financial_source_type TEXT
    CHECK (financial_source_type IS NULL OR financial_source_type IN (
      'document', 'subscription_payment_cycle', 'manual'
    )),
  ADD COLUMN IF NOT EXISTS financial_source_id UUID,
  -- Denormalized source document (also mirrored in entity_links) so the card /
  -- panel can render the linked document without a join.
  ADD COLUMN IF NOT EXISTS source_document_id UUID
    REFERENCES public.documents(id) ON DELETE SET NULL,
  -- The posted expense created by Mark-as-paid. Non-null == paid; this column is
  -- the idempotency guard (a second Mark-as-paid is a no-op).
  ADD COLUMN IF NOT EXISTS financial_transaction_id UUID
    REFERENCES public.money_transactions(id) ON DELETE SET NULL,
  -- Lifecycle of the FINANCIAL side, orthogonal to the task's own status.
  -- open -> paid | skipped | dismissed. (task_created/confirmed are implicit:
  -- the task existing == task_created.)
  ADD COLUMN IF NOT EXISTS financial_status TEXT NOT NULL DEFAULT 'open'
    CHECK (financial_status IN ('open', 'paid', 'skipped', 'dismissed')),
  ADD COLUMN IF NOT EXISTS financial_confidence NUMERIC(4, 3)
    CHECK (financial_confidence IS NULL OR (financial_confidence >= 0 AND financial_confidence <= 1)),
  ADD COLUMN IF NOT EXISTS financial_paid_at    TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS financial_skipped_at TIMESTAMPTZ;

COMMENT ON COLUMN public.todos.task_context_type IS
  'Financial context of the task. standard = ordinary todo (default). Non-standard values drive the Financial Tasks view and the Financial Context panel.';
COMMENT ON COLUMN public.todos.financial_due_date IS
  'Real payment/deadline date. Task due_date is set to financial_due_date - reminder_offset_days at creation.';
COMMENT ON COLUMN public.todos.reminder_offset_days IS
  'How many days before financial_due_date the task should surface. Default 3 (spec §10).';
COMMENT ON COLUMN public.todos.financial_transaction_id IS
  'Posted expense created by Mark-as-paid. Non-null == paid; serves as the idempotency guard against duplicate expenses.';
COMMENT ON COLUMN public.todos.financial_status IS
  'Financial lifecycle: open -> paid | skipped | dismissed. Distinct from task status (a paid task is also done).';

-- Guardrails: only financial tasks may carry a financial status/transaction.
ALTER TABLE public.todos
  DROP CONSTRAINT IF EXISTS todos_financial_context_consistency;
ALTER TABLE public.todos
  ADD CONSTRAINT todos_financial_context_consistency CHECK (
    task_context_type <> 'standard'
    OR (
      financial_due_date IS NULL
      AND amount IS NULL
      AND financial_transaction_id IS NULL
      AND financial_status = 'open'
    )
  );


-- ============================================================
-- B. Index the Financial Tasks access path
-- ============================================================
-- Partial index: only financial tasks, ordered by the date the user cares about.
CREATE INDEX IF NOT EXISTS todos_financial_tasks_idx
  ON public.todos (organization_id, financial_status, financial_due_date)
  WHERE task_context_type <> 'standard' AND deleted_at IS NULL;

-- Idempotency / dedupe lookups by source (one financial task per source obligation).
CREATE UNIQUE INDEX IF NOT EXISTS todos_financial_source_uniq
  ON public.todos (organization_id, financial_source_type, financial_source_id)
  WHERE financial_source_type IS NOT NULL
    AND financial_source_id IS NOT NULL
    AND deleted_at IS NULL;


-- ============================================================
-- C. Recreate task_smart_list so t.* picks up the new columns
-- ============================================================
-- The view (migration 061) is `SELECT t.*, ...`; t.* is expanded at CREATE time,
-- so it must be recreated for the new financial columns to appear in the view.
DROP VIEW IF EXISTS public.task_smart_list;
CREATE VIEW public.task_smart_list
  WITH (security_invoker = true)
  AS
SELECT
  t.*,
  CASE
    WHEN t.is_closed = 0
      AND t.due_date IS NOT NULL
      AND t.due_date < CURRENT_DATE
    THEN 0
    ELSE 1
  END                AS sort_overdue,
  p.name             AS project_name,
  p.color            AS project_color,
  p.status           AS project_status
FROM public.todos t
LEFT JOIN public.projects p ON p.id = t.project_id;

COMMENT ON VIEW public.task_smart_list IS
  'Read-only sortable projection of todos (now incl. financial-context columns). security_invoker: inherits todos/projects RLS. sort_overdue=0 for active overdue tasks.';

GRANT SELECT ON public.task_smart_list TO authenticated;


-- ============================================================
-- D. mark_financial_task_paid() — atomic one-off Mark-as-paid
-- ============================================================
-- Runs the money-critical steps in ONE transaction for a one-off financial task
-- (no subscription cycle):
--   1. authz + tenant guards
--   2. lock task, enforce idempotency (already paid -> no-op, returns existing tx)
--   3. create the posted expense (amount/currency re-read from the task row,
--      never trusted from the client)
--   4. link the transaction on the task + mark financial_status/status
--
-- Entity-links, domain events and audit logs are created by the caller AFTER
-- this returns (best-effort, repairable — must not hold a money transaction open).
CREATE OR REPLACE FUNCTION public.mark_financial_task_paid(
  p_organization_id   UUID,
  p_task_id           UUID,
  p_account_id        UUID,
  p_paid_date         DATE,
  p_category_id       UUID,
  p_transaction_title TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_task        public.todos%ROWTYPE;
  v_tx_id       UUID;
  v_paid        DATE := COALESCE(p_paid_date, current_date);
  v_cat_id      UUID;
  v_cat_source  TEXT;
  v_cat_status  TEXT;
BEGIN
  -- 1. Authz + tenant guard.
  IF auth.uid() IS NULL OR NOT public.is_org_member(p_organization_id) THEN
    RAISE EXCEPTION 'not_authorized' USING ERRCODE = '42501';
  END IF;
  IF NOT public.can_write_data(p_organization_id) THEN
    RAISE EXCEPTION 'not_authorized' USING ERRCODE = '42501';
  END IF;

  -- 2. Lock the task (serializes concurrent double-clicks) and scope to org.
  SELECT * INTO v_task
  FROM public.todos
  WHERE id = p_task_id AND organization_id = p_organization_id AND deleted_at IS NULL
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'task_not_found' USING ERRCODE = 'P0002';
  END IF;

  IF v_task.task_context_type = 'standard' THEN
    RAISE EXCEPTION 'not_a_financial_task' USING ERRCODE = 'P0001';
  END IF;

  -- Idempotency: an already-paid task returns its existing transaction, no writes.
  IF v_task.financial_status = 'paid' THEN
    RETURN jsonb_build_object(
      'already_paid', true,
      'task_id', v_task.id,
      'transaction_id', v_task.financial_transaction_id
    );
  END IF;

  IF v_task.financial_status <> 'open' THEN
    RAISE EXCEPTION 'task_not_payable' USING ERRCODE = 'P0001',
      DETAIL = format('financial_status=%s', v_task.financial_status);
  END IF;

  IF v_task.amount IS NULL OR v_task.amount <= 0 OR v_task.currency IS NULL THEN
    RAISE EXCEPTION 'task_missing_amount' USING ERRCODE = 'P0001';
  END IF;

  -- Verify the paying account belongs to the same org.
  IF NOT EXISTS (
    SELECT 1 FROM public.money_accounts a
    WHERE a.id = p_account_id AND a.organization_id = p_organization_id AND a.deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'account_not_found' USING ERRCODE = 'P0002';
  END IF;

  -- Optional category must also be in-org; otherwise fall back to uncategorized.
  v_cat_id := NULL;
  IF p_category_id IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.money_categories c
    WHERE c.id = p_category_id AND c.organization_id = p_organization_id
  ) THEN
    v_cat_id := p_category_id;
  END IF;

  IF v_cat_id IS NOT NULL THEN
    v_cat_source := 'system';
    v_cat_status := 'confirmed';
  ELSE
    v_cat_source := NULL;
    v_cat_status := 'uncategorized';
  END IF;

  -- 3. Create the posted expense. amount/currency come from the LOCKED task row
  --    (server-authoritative), so the posted amount can never be spoofed.
  INSERT INTO public.money_transactions (
    organization_id, workspace_id, created_by, updated_by,
    account_id, category_id, category_source, categorization_status,
    type, status, amount, currency, transaction_date, title,
    source_document_id
  ) VALUES (
    p_organization_id, v_task.workspace_id, auth.uid(), auth.uid(),
    p_account_id, v_cat_id, v_cat_source, v_cat_status,
    'expense', 'posted', v_task.amount, v_task.currency, v_paid,
    COALESCE(NULLIF(btrim(p_transaction_title), ''), v_task.title),
    v_task.source_document_id
  )
  RETURNING id INTO v_tx_id;

  -- 4. Mark the task paid + completed and link the transaction.
  UPDATE public.todos
  SET financial_status = 'paid',
      financial_transaction_id = v_tx_id,
      financial_paid_at = now(),
      status = 'done',
      is_completed = true,
      updated_by = auth.uid()
  WHERE id = v_task.id;

  RETURN jsonb_build_object(
    'already_paid', false,
    'task_id', v_task.id,
    'transaction_id', v_tx_id,
    'workspace_id', v_task.workspace_id,
    'source_document_id', v_task.source_document_id,
    'amount', v_task.amount,
    'currency', v_task.currency
  );
END;
$$;

REVOKE ALL ON FUNCTION public.mark_financial_task_paid(UUID, UUID, UUID, DATE, UUID, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.mark_financial_task_paid(UUID, UUID, UUID, DATE, UUID, TEXT) TO authenticated;

COMMIT;
