import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { CurrentContext } from "@/lib/context/current-context";
import { canDo } from "@/lib/context/current-context";
import { createDocumentWithAttachments } from "@/modules/documents/services/document-upload-service";
import { hasDocumentPermission } from "@/modules/documents/services/document-permissions";
import { createSourcedPlannerEntry } from "./create-sourced-planner-entry";
import type { PlannerEntryType } from "../types/planner.types";

/**
 * Inbox binary capture orchestration.
 *
 * The Inbox owns *capture*; Documents owns *files*. This service is the seam: it
 * hands the bytes to the shared Documents upload service (the single owner of
 * storage, validation, billing, rollback, events and extraction) and then links
 * the resulting Document to exactly one sourced planner entry.
 *
 * Money safety: there is no path from here to money_transactions. Extraction may
 * produce a reviewable draft, but only an explicit user confirmation posts money.
 *
 * Partial-outcome rule (design Phase 4): a Document that stored successfully is
 * NEVER deleted just because planner linking failed. Linking failure returns a
 * recoverable warning with the document id so the reconciler / a retry can finish
 * the link, rather than losing the user's file.
 */

export interface CaptureInboxDocumentInput {
  files: File[];
  /** Stable client-generated idempotency token for this capture attempt. */
  captureId: string;
  /** Optional free-text context the user typed alongside the file(s). */
  note?: string | null;
  /** 'photo' for the camera mode, 'document' for the file mode. */
  entryType: Extract<PlannerEntryType, "photo" | "document">;
  /** Human-readable capture title (generated by the caller from filename/date). */
  title: string;
}

export type CaptureInboxDocumentResult =
  | { ok: false; status: number; error: string; diagnosticId?: string }
  | {
      ok: true;
      documentId: string;
      /** Null only when the Document stored but planner linking failed (recoverable). */
      entryId: string | null;
      reused: boolean;
      /** Present when the Document is safe but its planner entry could not be created. */
      warning?: string;
    };

export async function captureInboxDocument(
  supabase: SupabaseClient,
  ctx: CurrentContext,
  input: CaptureInboxDocumentInput,
): Promise<CaptureInboxDocumentResult> {
  // Both permissions are required: the capture creates a planner entry AND a
  // Document. Checked here (not trusted from the client) before any storage work.
  if (!canDo(ctx, "planner.entry.create")) {
    return { ok: false, status: 403, error: "You do not have permission to capture entries." };
  }
  if (!hasDocumentPermission(ctx, "document.create") || !hasDocumentPermission(ctx, "document.attachment.upload")) {
    return { ok: false, status: 403, error: "You do not have permission to create documents." };
  }

  // Documents owns the file. doc_type stays 'unknown' — the composer does not ask
  // the user to classify; extraction reads it and classifies honestly, and an
  // unreadable type fails fast into a manual-review state. queueExtraction is
  // forced on so every captured file is read (or honestly marked unreadable).
  const upload = await createDocumentWithAttachments(supabase, ctx, {
    input: { title: input.title, description: (input.note ?? "").trim(), doc_type: "unknown", entity_type: null, entity_id: null },
    files: input.files,
    inboxCaptureId: input.captureId,
    source: "inbox",
    queueExtraction: true,
  });

  if (!upload.ok) {
    return { ok: false, status: upload.status, error: upload.error, diagnosticId: upload.diagnosticId };
  }

  // Link the Document to exactly one capture entry. Reuse on retry is guaranteed
  // by the migration-105 unique index; the summary is the note (if any) plus the
  // document title so the Inbox list has something human to show.
  const summary = (input.note ?? "").trim() || input.title;
  const entryResult = await createSourcedPlannerEntry(supabase, ctx, {
    entity: { kind: "document", id: upload.documentId },
    summary,
    entryType: input.entryType,
    // Extraction is running (or has been queued); the card reflects live state.
    status: upload.extractionQueued ? "processing" : "suggested",
  });

  if (!entryResult.ok) {
    // The file is safe. Do not delete it; return a recoverable warning so the
    // reconciler (or the user retrying with the same capture id) can finish.
    return {
      ok: true,
      documentId: upload.documentId,
      entryId: null,
      reused: upload.reused,
      warning: "Your file was saved to Documents, but we couldn't add it to your Inbox yet. It will appear shortly.",
    };
  }

  return { ok: true, documentId: upload.documentId, entryId: entryResult.entry.id, reused: upload.reused };
}

/**
 * Repair captures where the Document stored but its planner entry never got
 * created (a crash/failure between the two writes). Idempotent and owner-scoped:
 * finds recent Inbox-origin Documents with no linked capture entry and creates
 * the missing link. Best-effort — a failure here never blocks the caller.
 */
export async function reconcileInboxDocumentCaptures(
  supabase: SupabaseClient,
  ctx: CurrentContext,
  limit = 10,
): Promise<{ repaired: number }> {
  const { data: documents } = await supabase
    .from("documents")
    .select("id, title")
    .eq("organization_id", ctx.org.id)
    .eq("created_by", ctx.user.id)
    .not("inbox_capture_id", "is", null)
    .is("deleted_at", null)
    .order("created_at", { ascending: false })
    .limit(limit);
  if (!documents?.length) return { repaired: 0 };

  const documentIds = documents.map((d) => d.id as string);
  const { data: linked } = await supabase
    .from("planner_entries")
    .select("source_document_id")
    .eq("organization_id", ctx.org.id)
    .eq("owner_user_id", ctx.user.id)
    .in("source_document_id", documentIds);
  const linkedIds = new Set((linked ?? []).map((r) => r.source_document_id as string));

  let repaired = 0;
  for (const doc of documents) {
    const id = doc.id as string;
    if (linkedIds.has(id)) continue;
    const result = await createSourcedPlannerEntry(supabase, ctx, {
      entity: { kind: "document", id },
      summary: (doc.title as string) || "Document capture",
      entryType: "document",
      status: "processing",
    });
    if (result.ok && !result.reused) repaired += 1;
  }
  return { repaired };
}
